source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'swift-lateral-toolbox_Example', :exclusive => true do
  pod 'swift-lateral-toolbox', :path => '../'
end

target 'swift-lateral-toolbox_Tests', :exclusive => true do
  pod 'swift-lateral-toolbox', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'Nimble-Snapshots'
end
